name: tripperflow
description: Aplicación móvil informativa de las capitales de Centroamérica y sus principales lugares turísticos.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #Firebase dependencies
  firebase_core: ^0.5.0
  cloud_firestore: ^0.14.0+2
  firebase_storage: ^4.0.0
  firebase_auth: ^0.18.0+1

  # Custom dependencies
  flutter_staggered_grid_view: ^0.3.2
  flutter_bloc: ^6.0.5
  equatable: ^1.2.5
  provider: ^4.3.2+2
  cached_network_image: ^2.3.2+1
  shared_preferences: ^0.5.12


  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/Tripperflow-Logo.png

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-Thin.ttf
          style: normal
          weight: 100

        - asset: assets/fonts/Montserrat/Montserrat-ThinItalic.ttf
          style: italic
          weight: 100

        - asset: assets/fonts/Montserrat/Montserrat-ExtraLight.ttf
          style: normal
          weight: 200

        - asset: assets/fonts/Montserrat/Montserrat-ExtraLightItalic.ttf
          style: italic
          weight: 200

        - asset: assets/fonts/Montserrat/Montserrat-Light.ttf
          style: normal
          weight: 300

        - asset: assets/fonts/Montserrat/Montserrat-LightItalic.ttf
          style: italic
          weight: 300

        - asset: assets/fonts/Montserrat/Montserrat-Regular.ttf
          style: normal
          weight: 400

        - asset: assets/fonts/Montserrat/Montserrat-Medium.ttf
          style: normal
          weight: 500

        - asset: assets/fonts/Montserrat/Montserrat-MediumItalic.ttf
          style: italic
          weight: 500

        - asset: assets/fonts/Montserrat/Montserrat-SemiBold.ttf
          style: normal
          weight: 600

        - asset: assets/fonts/Montserrat/Montserrat-SemiBoldItalic.ttf
          style: italic
          weight: 600

        - asset: assets/fonts/Montserrat/Montserrat-Bold.ttf
          style: normal
          weight: 700

        - asset: assets/fonts/Montserrat/Montserrat-BoldItalic.ttf
          style: italic
          weight: 700

        - asset: assets/fonts/Montserrat/Montserrat-ExtraBold.ttf
          style: normal
          weight: 800

        - asset: assets/fonts/Montserrat/Montserrat-ExtraBoldItalic.ttf
          style: italic
          weight: 800

        - asset: assets/fonts/Montserrat/Montserrat-Black.ttf
          style: normal
          weight: 900

        - asset: assets/fonts/Montserrat/Montserrat-BlackItalic.ttf
          style: italic
          weight: 900
